// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VsBNBPwnAAjK4fA6AWmsbp-dUf1dZOo',
    appId: '1:607583469500:web:5209137433f1c1740af5b9',
    messagingSenderId: '607583469500',
    projectId: 'medapp-f9798',
    authDomain: 'medapp-f9798.firebaseapp.com',
    storageBucket: 'medapp-f9798.appspot.com',
    measurementId: 'G-NMH5TXJNJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmi6kjQu2Pz9KCTbPY8WQyk2o0xJlMeqI',
    appId: '1:607583469500:android:76345c7faf1580c10af5b9',
    messagingSenderId: '607583469500',
    projectId: 'medapp-f9798',
    storageBucket: 'medapp-f9798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7utvLi9LlF26-TMk6j-S9M0CXDB1nok',
    appId: '1:607583469500:ios:75b569bbc07060810af5b9',
    messagingSenderId: '607583469500',
    projectId: 'medapp-f9798',
    storageBucket: 'medapp-f9798.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM7utvLi9LlF26-TMk6j-S9M0CXDB1nok',
    appId: '1:607583469500:ios:2a5800e31fd288a60af5b9',
    messagingSenderId: '607583469500',
    projectId: 'medapp-f9798',
    storageBucket: 'medapp-f9798.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
